apiVersion: hexdag/v1
kind: Pipeline
metadata:
  name: deep-research-agent-staging
  description: Deep research agent with web search capabilities (STAGING)
spec:
  ports:
    llm:
      adapter: hexdag.builtin.adapters.openai.OpenAIAdapter
      config:
        api_key: ${STAGING_OPENAI_API_KEY}
        model: gpt-4o-mini
        temperature: 0.7
    tool_router:
      adapter: hexdag.builtin.adapters.mock.MockToolRouter
      config:
        available_tools:
        - search
        - calculate
  nodes:
  - kind: macro_invocation
    metadata:
      name: research_agent
    spec:
      macro: hexdag.builtin.macros.ReasoningAgentMacro
      config:
        main_prompt: 'You are a deep research agent. Research the following question
          thoroughly: {{research_question}}'
        max_steps: 5
        allowed_tools:
        - search
        - calculate
        tool_format: mixed
    dependencies: []
