apiVersion: hexdag/v1
kind: Pipeline
metadata:
  name: deep-research-agent-dev
  description: Deep research agent with web search capabilities (DEV - Mock Adapters)
spec:
  ports:
    llm:
      adapter: hexdag.builtin.adapters.mock.MockLLM
      config:
        responses:
        - 'I''ll search for information. INVOKE_TOOL: search(query=''...'')'
        - 'Let me gather more details. INVOKE_TOOL: search(query=''...'')'
        - 'Based on research, here are my findings: [Mock comprehensive answer]'
        delay_seconds: 0.1
    tool_router:
      adapter: hexdag.builtin.adapters.mock.MockToolRouter
      config:
        available_tools:
        - search
        - calculate
  nodes:
  - kind: macro_invocation
    metadata:
      name: research_agent
    spec:
      macro: hexdag.builtin.macros.ReasoningAgentMacro
      config:
        main_prompt: 'You are a deep research agent. Research the following question
          thoroughly: {{research_question}}'
        max_steps: 5
        allowed_tools:
        - search
        - calculate
        tool_format: mixed
    dependencies: []
