apiVersion: hexdag/v1
kind: Pipeline
metadata:
  name: deep-research-agent-prod
  description: Deep research agent with web search capabilities (PRODUCTION)
spec:
  ports:
    llm:
      adapter: open_ai_adapter
      config:
        api_key: ${OPENAI_API_KEY}
        model: gpt-4o
        temperature: 0.7
    tool_router:
      adapter: tool_router
      config: {}
  nodes:
  - kind: macro_invocation
    metadata:
      name: research_agent
    spec:
      macro: core:reasoning_agent
      config:
        main_prompt: 'You are a deep research agent. Research the following question
          thoroughly: {{research_question}}'
        max_steps: 5
        allowed_tools:
        - search
        - calculate
        tool_format: mixed
    dependencies: []
