# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    uv: "1"

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py

# Python dependencies
python:
  install:
  - method: uv
    path: pyproject.toml
    extras:
    - dev
