name: text2sql_pipeline
description: Intelligent Text-to-SQL generation with agent-based reasoning and tool usage

nodes:
  # Single agent node that handles the entire Text-to-SQL workflow with internal LoopNode
  - type: agent
    id: text2sql_agent
    params:
      initial_prompt_template: |
        You are a Text-to-SQL expert. Your goal: convert natural language questions into precise SQL queries.

        Question: {{question}}
        Database: {{database_name}}

        Process:
        1. Understand the question - identify entities, metrics, relationships
        2. Explore database schema using available tools
        3. Build intermediate understanding of required data
        4. Generate accurate SQL query

        Use tools when you need information. Think step by step.

        When you have completed the analysis and generated the SQL, call the END tool:
        INVOKE_TOOL: tool_end(sql_query="SELECT ...", explanation="Brief explanation", confidence="high|medium|low")

      continuation_prompt_template:
        default: |
          Continue working on the Text-to-SQL task.

          Original Question: {{question}}
          Database: {{database_name}}

          Previous steps:
          {{reasoning_steps}}

          Continue your analysis and generate the SQL query when ready. Use available tools as needed.

          When ready to provide final results, call the END tool:
          INVOKE_TOOL: tool_end(sql_query="SELECT ...", explanation="Brief explanation", confidence="high|medium|low")

      max_steps: 8

      input_schema:
        question: str
        database_name: str

      output_schema:
        sql_query: str
        explanation: str
        confidence: str
    depends_on: []
