name: parallel_test_pipeline
description: Verify parallel execution with timing measurements - Refactored with Input Mappings

nodes:
  # Wave 1: Setup and initialization (1 node)
  - type: function
    id: timer_setup
    params:
      fn: setup_timer
    depends_on: []

  # Wave 2: Parallel execution tasks (2 nodes running simultaneously)
  - type: function
    id: task_a_processor
    params:
      fn: slow_task_a
      input_mapping:
        timer_data: "timer_setup"
    depends_on: [timer_setup]

  - type: function
    id: task_b_processor
    params:
      fn: slow_task_b
      input_mapping:
        timer_data: "timer_setup"
    depends_on: [timer_setup]

  # Wave 3: Analysis and verification (1 node waiting for both tasks)
  - type: function
    id: parallel_analyzer
    params:
      fn: timing_analyzer
      input_mapping:
        task_a_result: "task_a_processor"
        task_b_result: "task_b_processor"
        timer_data: "timer_setup"
    depends_on: [task_a_processor, task_b_processor]

  # Wave 4: Final result aggregation
  - type: function
    id: result_aggregator_node
    params:
      fn: result_aggregator
      input_mapping:
        timing_analysis: "parallel_analyzer"
        task_a_result: "task_a_processor"
        task_b_result: "task_b_processor"
        setup_timer: "timer_setup"
    depends_on: [parallel_analyzer]
