name: dummy_pipeline
description: Comprehensive Type-Safe Pipeline with Functions, LLMs, and Agents - Refactored with Input Mappings

# Pipeline-wide field mapping configuration
field_mapping_mode: "default" # Options: "none", "default", "custom"

# Custom field mappings (only used if field_mapping_mode: "custom")
# custom_field_mappings:
#   text: ["content", "data", "input"]
#   result: ["output", "response"]

nodes:
  # 1. Function node - schemas auto-inferred from Pydantic
  - type: function
    id: input_validator
    params:
      fn: validate_input
      # Auto-infers: DummyPipelineInput → ValidatedOutput
    depends_on: []

  # 2. LLM node - structured output with explicit schema (auto-converted)
  - type: llm
    id: sentiment_analyzer
    params:
      prompt_template: |
        Analyze the sentiment and emotional tone of this text:
        Text: {{text}}
        Priority: {{priority}}

        Provide a detailed sentiment analysis with enhanced emotional intelligence.
      input_mapping:
        text: "input_validator.text"
        priority: "input_validator.priority"
      output_schema:
        sentiment: str # positive, negative, neutral
        confidence: float # 0.0 to 1.0
        emotions: list[str] # detected emotions
        tone: str # formal, casual, technical, etc.
    depends_on: [input_validator]

  # 3. Function node - feature extraction with explicit mapping
  - type: function
    id: feature_extractor
    params:
      fn: extract_features
      input_mapping:
        validated_data: "input_validator"
      # Auto-infers: ValidatedOutput → FeaturesOutput
    depends_on: [input_validator]

  # 4. Agent node - reasoning agent with explicit input mapping
  - type: agent
    id: quality_advisor
    params:
      max_steps: 8
      available_tools: []
      prompt_template: |
        Goal: Provide comprehensive quality advice for the text

        You will analyze text features and sentiment to provide actionable recommendations.
      input_mapping:
        features: "feature_extractor"
        sentiment_analysis: "sentiment_analyzer"
      # Agents auto-infer: input data → {result: Any, reasoning: str}
    depends_on: [feature_extractor, sentiment_analyzer]

  # 5. Function node - score calculation with explicit mapping
  - type: function
    id: score_calculator
    params:
      fn: calculate_score
      input_mapping:
        features_data: "feature_extractor"
      # Auto-infers: FeaturesOutput → ScoreOutput
    depends_on: [feature_extractor]

  # 6. LLM node - final insights with structured output and explicit mapping
  - type: llm
    id: insights_generator
    params:
      prompt_template: |
        Based on all analyses, generate final insights:

        Quality Score: {{quality_score}}
        Sentiment: {{sentiment}} ({{confidence}})
        Advisor Recommendations: {{advisor_result}}

        Provide comprehensive insights and next steps.
      input_mapping:
        quality_score: "score_calculator.quality_score"
        sentiment: "sentiment_analyzer.sentiment"
        confidence: "sentiment_analyzer.confidence"
        advisor_result: "quality_advisor.result"
      output_schema:
        key_insights: list[str]
        action_items: list[str]
        overall_assessment: str
        confidence_level: float
    depends_on: [score_calculator, sentiment_analyzer, quality_advisor]

  # 7. Function node - final summary with explicit mapping
  - type: function
    id: summary_generator
    params:
      fn: generate_summary
      input_mapping:
        score_data: "score_calculator"
        insights_data: "insights_generator"
      # Auto-infers: ScoreOutput → SummaryOutput
    depends_on: [score_calculator, insights_generator]
