apiVersion: v1
kind: Pipeline
metadata:
  name: example-k8s-pipeline
  description: Example pipeline using K8s-style YAML format
  author: hexDAG Team
  version: "1.0"

spec:
  # Common field mappings for reusability
  common_field_mappings:
    user_query_mapping:
      user_query: input.query

  # Pipeline nodes
  nodes:
    # First node: Process user input
    - kind: function_node
      metadata:
        name: process_input
        annotations:
          description: Process and validate user input
      spec:
        fn: process_user_query
        dependencies: []

    # Second node: LLM analysis
    - kind: llm_node
      metadata:
        name: analyze_query
      spec:
        prompt_template: "Analyze this query: {{process_input.result}}"
        dependencies: [process_input]

    # Third node: Generate response
    - kind: llm_node
      metadata:
        name: generate_response
      spec:
        prompt_template: "Generate a response based on: {{analyze_query.response}}"
        dependencies: [analyze_query]

    # Fourth node: Format output (from external plugin)
    - kind: my-plugin:formatter_node
      metadata:
        name: format_output
      spec:
        format_type: markdown
        dependencies: [generate_response]
