trigger:
    branches:
      include:
        - main


pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: ConventionalCommits
    displayName: "Check conventional commits"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install uv"
      - script: |
          uvx --from commitizen cz check
        displayName: "cz check"

  - job: BuildAndPublish
    displayName: "Build package & publish to TestPyPI"
    dependsOn: CodeQuality
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    steps:
      - checkout: self
        clean: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"

      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install uv"

      - script: |
          uvx --from build pyproject-build
          uvx twine check dist/*
        displayName: "Build sdist & wheel"

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/dist"
          artifact: "dist"
          publishLocation: "pipeline"
        displayName: "Save dist/ as artifact"

      - script: |
          set -e
          TWINE_USERNAME="__token__" \
          TWINE_PASSWORD="$(TEST_PYPI_TOKEN)" \
          uvx twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        displayName: "Upload to TestPyPI"

      - script: |
          set -e
          INFO="$(uv version)"
          PKG_NAME="$(echo "$INFO" | awk '{print $1}')"
          PKG_VERSION="$(echo "$INFO" | awk '{print $2}')"

          echo "Detected: $PKG_NAME $PKG_VERSION"
          echo "##vso[task.setvariable variable=PKG_NAME]$PKG_NAME"
          echo "##vso[task.setvariable variable=PKG_VERSION]$PKG_VERSION"
        displayName: "Read package name/version (uv)"

      - script: |
          set -e
          uv venv .venv_test
          source .venv_test/bin/activate
          uv pip install \
            --index-url https://test.pypi.org/simple \
            --extra-index-url https://pypi.org/simple \
            $(PKG_NAME)==$(PKG_VERSION)

          # smoke test: check installed version
          uv pip show $(PKG_NAME) | grep Version:
        displayName: "Install from TestPyPI + smoke test (uv)"
        env:
          PKG_NAME: $(PKG_NAME)
          PKG_VERSION: $(PKG_VERSION)
        condition: succeeded()

  - job: BuildMatrix
    displayName: "Build sdist & universal wheel on Linux/Windows/macOS"
    strategy:
      matrix:
        linux:
          image: "ubuntu-latest"
        windows:
          image: "windows-latest"
        macos:
          image: "macos-latest"
    pool:
      vmImage: $(image)

    steps:
      - checkout: self
        clean: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"

      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install uv"

      - script: |
          uvx --from build pyproject-build
        displayName: "Build sdist & wheel"

      - script: |
          uvx twine check dist/*
        displayName: "Twine check"

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/dist"
          artifact: "dist-$(Agent.OS)"
          publishLocation: "pipeline"
        displayName: "Publish dist/ as artifact"

  - job: InstallSmoke
    displayName: "Smoke test install dist on Linux/Windows/macOS"
    dependsOn: BuildMatrix
    strategy:
      matrix:
        linux:
          image: "ubuntu-latest"
        windows:
          image: "windows-latest"
        macos:
          image: "macos-latest"
    pool:
      vmImage: $(image)

    steps:
      - checkout: none

      - download: current
        artifact: dist-$(Agent.OS)

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"

      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install uv"

      - script: |
          uv venv .venv_test
          source .venv_test/bin/activate || .venv_test\Scripts\activate
          if ls dist-$(Agent.OS)/*.whl 1> /dev/null 2>&1; then
            uv pip install dist-$(Agent.OS)/*.whl
          else
            uv pip install dist-$(Agent.OS)/*.tar.gz
          fi
          python -c "import hexai; print('hexai import ok')"
        shell: bash
        displayName: "Install from artifact (wheel or sdist) + import check"

  - job: DocsArtifacts
    displayName: "Publish packaging docs artifacts"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        clean: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/CHANGELOG.md"
          artifact: "CHANGELOG"
          publishLocation: "pipeline"
        displayName: "Publish CHANGELOG.md"
      - task: PublishPipelineArtifact@1
        condition: exists('$(System.DefaultWorkingDirectory)/docs/PACKAGING_PLAN.md')
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/docs/PACKAGING_PLAN.md"
          artifact: "PACKAGING_PLAN"
          publishLocation: "pipeline"
        displayName: "Publish PACKAGING_PLAN.md (if present)"


  - job: DeptryReport
    displayName: "Deptry dependency report"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        clean: true
      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install uv"
      - script: |
          uv venv .venv && source .venv/bin/activate
          uv pip install deptry
          uv run deptry hexai > deptry_report.txt || true
        displayName: "Run deptry (collect issues)"
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/deptry_report.txt"
          artifact: "DEPTRY_REPORT"
          publishLocation: "pipeline"
        displayName: "Publish deptry report"

  - job: PublishProdPyPI
    displayName: "Publish to PyPI (manual)"
    dependsOn: BuildMatrix
    condition: and(succeeded(), false)   # turn off
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        clean: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"
      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install uv"
      - download: current
        artifact: dist-ubuntu
      - script: |
          uvx twine check dist-ubuntu/*
        displayName: "Twine check"
      - script: |
          TWINE_USERNAME="__token__" \
          TWINE_PASSWORD="$(PYPI_TOKEN)" \
          uvx twine upload dist-ubuntu/*
        displayName: "Upload to PyPI"

  - job: ReleaseNotes
    displayName: "Generate release notes (from conventional commits)"
    pool: { vmImage: 'ubuntu-latest' }
    steps:
      - checkout: self
      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install uv"
      - script: |
          uvx --from commitizen cz changelog --unreleased --dry-run > RELEASE_NOTES.md || true
        displayName: "Build release notes (unreleased)"
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/RELEASE_NOTES.md"
          artifact: "RELEASE_NOTES"
          publishLocation: "pipeline"
        displayName: "Publish release notes"
