trigger:
    branches:
      include:
        - main


pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildAndPublish
    displayName: "Build package & publish to TestPyPI"
    dependsOn: CodeQuality
    steps:
      - checkout: self
        clean: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"

      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install uv"

      - script: |
          uvx --from build pyproject-build
          uv run twine check dist/*
        displayName: "Build sdist & wheel"

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/dist"
          artifact: "dist"
          publishLocation: "pipeline"
        displayName: "Save dist/ as artifact"

      - script: |
          set -e
          TWINE_USERNAME="__token__" \
          TWINE_PASSWORD="$(TEST_PYPI_TOKEN)" \
          uvx twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        displayName: "Upload to TestPyPI"

      - script: |
          set -e
          INFO="$(uv version)"
          PKG_NAME="$(echo "$INFO" | awk '{print $1}')"
          PKG_VERSION="$(echo "$INFO" | awk '{print $2}')"

          echo "Detected: $PKG_NAME $PKG_VERSION"
          echo "##vso[task.setvariable variable=PKG_NAME]$PKG_NAME"
          echo "##vso[task.setvariable variable=PKG_VERSION]$PKG_VERSION"
        displayName: "Read package name/version (uv)"

      - script: |
          set -e
          uv venv .venv_test
          source .venv_test/bin/activate
          uv pip install \
            --index-url https://test.pypi.org/simple \
            --extra-index-url https://pypi.org/simple \
            $(PKG_NAME)==$(PKG_VERSION)

          # smoke test: check installed version
          uv pip show $(PKG_NAME) | grep Version:
        displayName: "Install from TestPyPI + smoke test (uv)"
        env:
          PKG_NAME: $(PKG_NAME)
          PKG_VERSION: $(PKG_VERSION)
        condition: succeeded()

  - job: BuildMatrix
    displayName: "Build sdist & universal wheel on Linux/Windows/macOS"
    strategy:
      matrix:
        linux:
          image: "ubuntu-latest"
        windows:
          image: "windows-latest"
        macos:
          image: "macos-latest"
    pool:
      vmImage: $(image)

    steps:
      - checkout: self
        clean: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"

      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install uv"

      - script: |
          uvx --from build pyproject-build
        displayName: "Build sdist & wheel"

      - script: |
          uvx twine check dist/*
        displayName: "Twine check"

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/dist"
          artifact: "dist-$(Agent.OS)"
          publishLocation: "pipeline"
        displayName: "Publish dist/ as artifact"
