variables:
- group: pypi-secrets
- name: CI_USERNAME
  value: "CI Pipeline"
- name: CI_EMAIL
  value: developers@omniviser.ai

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: DevelopmentStandards
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - script: |
          # Define your naming convention regex pattern
          PATTERN="(^(chore|ci|docs|experiment|feat|fix|refactor|test)\/[A-Za-z0-9_-]+$)|main|^snyk|^dependabot"

          if [[ $(Build.Reason) == "PullRequest" ]]; then
            BRANCH="$(echo $(System.PullRequest.SourceBranch) | sed 's/refs\/heads\///')"
          else
            BRANCH="$(echo $(Build.SourceBranch) | sed 's/refs\/heads\///')"
          fi

          # Check if the branch name matches the pattern
          if [[ $BRANCH =~ $PATTERN ]]; then
              echo "Branch name '$BRANCH' is valid."
          else
              echo "Branch name [${BRANCH}] does not follow convention: [chore/* | ci/* | dependabot/* | docs/* | experiment/* | feat/* | fix/* | refactor/* | test/* | main | snyk | dependabot]."
              exit 1
          fi
        displayName: "Check the branch name"


      - script: |
          if [ "$BUILD_REASON" == "PullRequest" ] && [ "$TARGETBRANCH" == "refs/heads/main" ]; then
              echo "PullRequest reason for build"
              echo "Main target branch"

              pr_data=$(az repos pr show --id $PULLREQUESTID --organization $ORGANIZATION_URI)
              title=$(echo "$pr_data" | jq -r '.title')
              echo "PR Title: $title"
              echo "Keep in mind that 'Bump' and 'chore' are for AZURE BOTS ONLY, don't use them!"

              pattern="^(ci|docs|experiment|feat|fix|refactor|test|chore|Bump)"

              if [[ "$title" =~ $pattern ]]; then
                  echo "PR title is valid"
              else
                  echo "ERROR: PR TITLE IS INVALID"
                  echo "Please ensure your PR title starts with one of the following prefixes:"
                  echo "ci, Bump, docs, experiment, feat, fix, refactor, test, chore"
                  exit 1
              fi
          fi
        displayName: "Validate PR title"
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
          ORGANIZATION_URI: https://dev.azure.com/omniviser
          PULLREQUESTID: $(System.PullRequest.PullRequestId)
          TARGETBRANCH: $(System.PullRequest.TargetBranch)
          BUILD_REASON: $(Build.Reason)

  - job: CodeQuality
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"
        displayName: "Use Python 3.12"

      - bash: sudo apt-get install graphviz -f
        displayName: Install graphviz

      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install UV"

      - script: |
          uv run ruff check ./hexai --config pyproject.toml
        displayName: "Run Ruff linting (replaces flake8, isort)"

      - script: |
          uv run ruff format ./hexai --check
        displayName: "Run Ruff formatting check (replaces Black)"

      - script: |
          uv run mypy ./hexai
        displayName: "Run Mypy"

      - script: |
          uv run pyright ./hexai
        displayName: "Run Pyright"

      - script: |
          echo "Running tests with coverage..."
          uv run pytest ./tests --cov=./hexai --cov-report=xml:./coverage.xml --junitxml=./test-results.xml
        displayName: "Run unit tests"

      - script: |
          echo "Running Bandit for SAST..."
          uv run bandit -r ./hexai -x ./tests -f json -o bandit-report.json
          BANDIT_EXIT_CODE=$?
          echo "Bandit exit code: $BANDIT_EXIT_CODE"
          if [ $BANDIT_EXIT_CODE -ne 0 ]; then
              echo "Bandit found issues or encountered an error. See bandit-report.json for details."
              cat bandit-report.json
              exit 1
          fi
        displayName: "Run Bandit"

      - script: |
          uv run scripts/check_test_structure.py
        displayName: "Check test structure consistency"

      - script: |
          uv run scripts/check_examples.py
        displayName: "Check examples functionality"

      - script: |
          uv run deptry .
        displayName: "Run deptry"

      - script: |
          echo "Running Safety for dependency vulnerability scanning..."
          uv run safety check --output json > safety-report.json
          SAFETY_EXIT_CODE=$?
          echo "Safety exit code: $SAFETY_EXIT_CODE"
          if [ $SAFETY_EXIT_CODE -ne 0 ]; then
              echo "Safety found vulnerabilities. See safety-report.json for details."
              cat safety-report.json
              exit 1
          fi
        displayName: "Run Safety - dependency vulnerability scan"

      - script: |
          echo "Running Gitleaks for secret detection..."
          # Install gitleaks
          VERSION=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          echo "Installing Gitleaks version: $VERSION"
          curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz" | tar -xz -C /tmp
          /tmp/gitleaks detect --source . --report-format json --report-path gitleaks-report.json
          GITLEAKS_EXIT_CODE=$?
          echo "Gitleaks exit code: $GITLEAKS_EXIT_CODE"
          if [ $GITLEAKS_EXIT_CODE -ne 0 ]; then
              echo "Gitleaks found secrets or encountered an error. See gitleaks-report.json for details."
              cat gitleaks-report.json
              exit 1
          fi
        displayName: "Run Gitleaks - secret detection"

      - script: |
          echo "Running yamllint for YAML config quality..."
          uv run yamllint -d relaxed .
        displayName: "Run yamllint - YAML config quality"

      - script: |
          echo "Running vulture for dead code detection..."
          uv run vulture hexai/ --min-confidence 90
        displayName: "Run vulture - dead code detection"

      - script: |
          echo "Running radon for code complexity analysis..."
          uv run radon cc hexai/ --min B --show-complexity
        displayName: "Run radon - code complexity analysis"
