variables:
  CI_USERNAME: "CI Pipeline"
  CI_EMAIL: developers@omniviser.ai

trigger:
  branches:
    include:
      - main
      - feat/*

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: DevelopmentStandards
    displayName: "Development standards"
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - script: |
          # Define your naming convention regex pattern
          PATTERN="(^(chore|ci|docs|experiment|feat|fix|refactor|test)\/[A-Za-z0-9_-]+$)|main|^snyk|^dependabot"
          if [[ $(Build.Reason) == "PullRequest" ]]; then
            BRANCH="$(echo $(System.PullRequest.SourceBranch) | sed 's/refs\/heads\///')"
          else
            BRANCH="$(echo $(Build.SourceBranch) | sed 's/refs\/heads\///')"
          fi
          # Check if the branch name matches the pattern
          if [[ $BRANCH =~ $PATTERN ]]; then
            echo "Branch name '$BRANCH' is valid."
          else
            echo "Branch name [$BRANCH] does not follow convention."
            exit 1
          fi
        displayName: "Check the branch name"

      - script: |
          if [ "$BUILD_REASON" == "PullRequest" ] && [ "$TARGETBRANCH" == "refs/heads/main" ]; then
              echo "PullRequest reason for build"
              echo "Main target branch"
            pr_data=$(az repos pr show --id $PULLREQUESTID --organization $ORGANIZATION_URI)
            title=$(echo "$pr_data" | jq -r '.title')
              echo "PR Title: $title"
              echo "Keep in mind that 'Bump' and 'chore' are for AZURE BOTS ONLY, don't use them!"
            pattern="^(ci|docs|experiment|feat|fix|refactor|test|chore|Bump)"
            if [[ "$title" =~ $pattern ]]; then
              echo "PR title is valid"
            else
              echo "ERROR: PR TITLE IS INVALID"
                  echo "Please ensure your PR title starts with one of the following prefixes:"
                  echo "ci, Bump, docs, experiment, feat, fix, refactor, test, chore"
              exit 1
            fi
          fi
        displayName: "Validate PR title"
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
          ORGANIZATION_URI: https://dev.azure.com/omniviser
          PULLREQUESTID: $(System.PullRequest.PullRequestId)
          TARGETBRANCH: $(System.PullRequest.TargetBranch)
          BUILD_REASON: $(Build.Reason)

  - job: CodeQuality
    displayName: "Code quality (Ubuntu, Py 3.12)"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"
        displayName: "Use Python 3.12"

      - bash: sudo apt-get install graphviz -f
        displayName: Install graphviz

      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install UV"

      - script: uv venv
        displayName: "Create UV virtual environment"

      - script: uv pip install -e ".[viz]"
        displayName: "Install package (editable + viz deps)"

      - script: uv run black --check ./hexai
        displayName: "Check Black"

      - script: |
          uv run pre-commit install
          uv run pre-commit run flake8 --all-files
        displayName: "Run Flake8"

      - script: uv run isort ./hexai --check-only
        displayName: "Run Isort"

      - script: uv run mypy ./hexai
        displayName: "Run Mypy"

      - script: uv run ruff check ./hexai
        displayName: "Run Ruff ./hexai"

      - script: |
          echo "Running tests with coverage..."
          uv run pytest ./tests --cov=./hexai --cov-report=xml:./coverage.xml --junitxml=./test-results.xml
        displayName: "Run unit tests"

      - script: |
          echo "Running Bandit for SAST..."
          uv run bandit -r ./hexai -x ./tests -f json -o bandit-report.json
          BANDIT_EXIT_CODE=$?
          echo "Bandit exit code: $BANDIT_EXIT_CODE"
          if [ $BANDIT_EXIT_CODE -ne 0 ]; then
              echo "Bandit found issues or encountered an error. See bandit-report.json for details."
              cat bandit-report.json
              exit 1
          fi
        displayName: "Run Bandit"

      - script: uv run scripts/check_test_structure.py
        displayName: "Check test structure"

      - script: |
          uv run scripts/check_examples.py
        displayName: "Check examples"

      - script: |
          uv run deptry .
        displayName: "Run deptry"

  - job: CIMatrix
    displayName: "Matrix: OS × Python × profiles"
    strategy:
      matrix:
        ubuntu-py310: { vmImage: "ubuntu-latest", python: "3.10" }
        ubuntu-py311: { vmImage: "ubuntu-latest", python: "3.11" }
        ubuntu-py312: { vmImage: "ubuntu-latest", python: "3.12" }
        macos-py310: { vmImage: "macos-latest", python: "3.10" }
        macos-py311: { vmImage: "macos-latest", python: "3.11" }
        macos-py312: { vmImage: "macos-latest", python: "3.12" }
        windows-py310: { vmImage: "windows-latest", python: "3.10" }
        windows-py311: { vmImage: "windows-latest", python: "3.11" }
        windows-py312: { vmImage: "windows-latest", python: "3.12" }
    pool:
      vmImage: $(vmImage)
    variables:
      PACKAGE_NAME: "hexai"
      ARTIFACT_DIR: "artifacts"
      VENV_DIR: ".venv"
    steps:
      - checkout: self
        fetchDepth: 1

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python)"
          addToPath: true
        displayName: "Use Python $(python)"

      - script: |
          if [ "$(Agent.OS)" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y graphviz
          elif [ "$(Agent.OS)" = "Darwin" ]; then
            brew update
            brew install graphviz || true
          else
            echo "Ensure Graphviz installed if needed"
          fi
        displayName: "Install system deps"
        condition: ne(variables['Agent.OS'], 'Windows_NT')

      - task: PowerShell@2
        displayName: "Install system deps (Windows via winget)"
        condition: eq(variables['Agent.OS'], 'Windows_NT')
        inputs:
          targetType: inline
          script: |
            try {
              winget --version
            } catch {
              Write-Host "winget not available on this runner; skipping Graphviz install"
              exit 0
            }
            winget install --id Graphviz.Graphviz -e --silent || Write-Host "Graphviz may already be installed"

      - script: |
          set -e
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install UV (Unix)"
        condition: ne(variables['Agent.OS'], 'Windows_NT')

      - task: PowerShell@2
        displayName: "Install UV (Windows)"
        condition: eq(variables['Agent.OS'], 'Windows_NT')
        inputs:
          targetType: inline
          script: |
              powershell -ExecutionPolicy Bypass -c "irm https://astral.sh/uv/install.ps1 | iex"
              if (elseif (Test-Path "$env:USERPROFILE\.local\bin\uv.exe") {
                Write-Host "##vso[task.setvariable variable=UV_BIN_DIR]$env:USERPROFILE\.local\bin"
              } else {
                Write-Host "##vso[task.setvariable variable=UV_BIN_DIR]$env:USERPROFILE\.cargo\bin"
              }

      - script: |
          set -e
          CANDIDATES=("$HOME/.local/bin" "$HOME/.cargo/bin" "/Users/runner/.local/bin" "/Users/runner/.cargo/bin")
          FOUND=""
          for d in "${CANDIDATES[@]}"; do
            if [ -x "$d/uv" ]; then
              FOUND="$d"
              break
            fi
          done
          if [ -z "$FOUND" ]; then
            echo "uv not found in common dirs; listing for debug"
            ls -la "$HOME/.local/bin" || true
            ls -la "$HOME/.cargo/bin" || true
            # fallback
            FOUND="$HOME/.local/bin"
          fi
          echo "Using UV from: $FOUND"
          echo "##vso[task.setvariable variable=UV_BIN_DIR]$FOUND"
        displayName: "Locate UV and set PATH var"
        condition: ne(variables['Agent.OS'], 'Windows_NT')

      - script: |
          set -e
          export PATH="$UV_BIN_DIR:$PATH"
          which uv || true
          uv venv
        displayName: "Create UV virtual environment"
        condition: ne(variables['Agent.OS'], 'Windows_NT')

      - task: PowerShell@2
        displayName: "Create UV virtual environment (Windows)"
        condition: eq(variables['Agent.OS'], 'Windows_NT')
        inputs:
          targetType: inline
          script: |
              $env:PATH = "$env:UV_BIN_DIR;$env:PATH"
              uv venv
              uv --version
              uv run python --version

      - script: |
          set -e
          mkdir -p $(ARTIFACT_DIR)
        displayName: "Artifacts dir"

      # BASE
      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          echo "=== Install profile: base ==="
          uv pip install -e .
          uv run python -c "import importlib, sys, platform; importlib.import_module('$(PACKAGE_NAME)'); print('OK base', sys.version.split()[0], platform.platform())"
        displayName: "Install (base)"
        condition: ne(variables['Agent.OS'], 'Windows_NT')

      - task: PowerShell@2
        displayName: "Install (base, Windows)"
        condition: eq(variables['Agent.OS'], 'Windows_NT')
        inputs:
          targetType: inline
          script: |
            $env:PATH = "$env:UV_BIN_DIR;$env:PATH"
            uv pip install -e .
            uv run python -c "import importlib; importlib.import_module('$(PACKAGE_NAME)')"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run python scripts/measure_import_time.py --package $(PACKAGE_NAME) --out $(ARTIFACT_DIR)/$(Agent.OS)_py$(python)_base_import.json
        displayName: "Measure import time (base)"
        condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main'))

      - task: PowerShell@2
        displayName: "Measure import time (base, Windows)"
        condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main'))
        inputs:
          targetType: inline
          script: |
            $env:PATH = "$env:UV_BIN_DIR;$env:PATH"
            uv run python scripts/measure_import_time.py --package "$(PACKAGE_NAME)" --out "$(ARTIFACT_DIR)\$(Agent.OS)_py$(python)_base_import.json"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run python scripts/size_benchmark.py --package $(PACKAGE_NAME) --out $(ARTIFACT_DIR)/$(Agent.OS)_py$(python)_base_size.json
        displayName: "Size benchmark (base)"
        condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main'))

      - task: PowerShell@2
        displayName: "Size benchmark (base, Windows)"
        condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main'))
        inputs:
          targetType: inline
          script: |
            $env:PATH = "$env:UV_BIN_DIR;$env:PATH"
            uv run python scripts/size_benchmark.py --package "$(PACKAGE_NAME)" --out "$(ARTIFACT_DIR)\$(Agent.OS)_py$(python)_base_size.json"

      # CLI
      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          echo "=== Install profile: cli ==="
          uv pip install -e ".[cli]"
          uv run python -c "import importlib, sys, platform; importlib.import_module('$(PACKAGE_NAME)'); print('OK cli', sys.version.split()[0], platform.platform())"
        displayName: "Install (cli)"
        condition: ne(variables['Agent.OS'], 'Windows_NT')

      - task: PowerShell@2
        displayName: "Install (cli, Windows)"
        condition: eq(variables['Agent.OS'], 'Windows_NT')
        inputs:
          targetType: inline
          script: |
              $env:PATH = "$env:UV_BIN_DIR;$env:PATH"
              uv pip install -e ".[cli]"
              uv run python -c "import importlib; importlib.import_module('$(PACKAGE_NAME)')"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run python scripts/measure_import_time.py --package $(PACKAGE_NAME) --out $(ARTIFACT_DIR)/$(Agent.OS)_py$(python)_cli_import.json
        displayName: "Measure import time (cli)"
        condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main')

      - task: PowerShell@2
        displayName: "Measure import time (cli, Windows)"
        condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main'))
        inputs:
          targetType: inline
          script: |
            $env:PATH = "$env:UV_BIN_DIR;$env:PATH"
            uv run python scripts/measure_import_time.py --package "$(PACKAGE_NAME)" --out "$(ARTIFACT_DIR)\$(Agent.OS)_py$(python)_cli_import.json"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run python scripts/size_benchmark.py --package $(PACKAGE_NAME) --out $(ARTIFACT_DIR)/$(Agent.OS)_py$(python)_cli_size.json
        displayName: "Size benchmark (cli)"
        condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main'))

      - task: PowerShell@2
        displayName: "Size benchmark (cli, Windows)"
        condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main'))
        inputs:
          targetType: inline
          script: |
            $env:PATH = "$env:UV_BIN_DIR;$env:PATH"
            uv run python scripts/size_benchmark.py --package "$(PACKAGE_NAME)" --out "$(ARTIFACT_DIR)\$(Agent.OS)_py$(python)_cli_size.json"

      # VIZ
      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          echo "=== Install profile: viz ==="
          uv pip install -e ".[viz]"
          uv run python -c "import importlib, sys, platform; importlib.import_module('$(PACKAGE_NAME)'); print('OK viz', sys.version.split()[0], platform.platform())"
        displayName: "Install (viz)"
        condition: ne(variables['Agent.OS'], 'Windows_NT')

      - task: PowerShell@2
        displayName: "Install (viz, Windows)"
        condition: eq(variables['Agent.OS'], 'Windows_NT')
        inputs:
          targetType: inline
          script: |
            $env:PATH = "$env:UV_BIN_DIR;$env:PATH"
            uv pip install -e ".[viz]"
            uv run python -c "import importlib; importlib.import_module('$(PACKAGE_NAME)')"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run python scripts/measure_import_time.py --package $(PACKAGE_NAME) --out $(ARTIFACT_DIR)/$(Agent.OS)_py$(python)_viz_import.json
        displayName: "Measure import time (viz)"
        condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main'))

      - task: PowerShell@2
        displayName: "Measure import time (viz, Windows)"
        condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main'))
        inputs:
          targetType: inline
          script: |
            $env:PATH = "$env:UV_BIN_DIR;$env:PATH"
            uv run python scripts/measure_import_time.py --package "$(PACKAGE_NAME)" --out "$(ARTIFACT_DIR)\$(Agent.OS)_py$(python)_viz_import.json"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run python scripts/size_benchmark.py --package $(PACKAGE_NAME) --out $(ARTIFACT_DIR)/$(Agent.OS)_py$(python)_viz_size.json
        displayName: "Size benchmark (viz)"
        condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main'))

      - task: PowerShell@2
        displayName: "Size benchmark (viz, Windows)"
        condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['Build.SourceBranchName'], 'main'))
        inputs:
          targetType: inline
          script: |
            $env:PATH = "$env:UV_BIN_DIR;$env:PATH"
            uv run python scripts/size_benchmark.py --package "$(PACKAGE_NAME)" --out "$(ARTIFACT_DIR)\$(Agent.OS)_py$(python)_viz_size.json"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(ARTIFACT_DIR)"
          ArtifactName: "benchmarks_$(Agent.OS)_py$(python)"
          publishLocation: "Container"
        displayName: "Publish artifacts"
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
