# Azure Pipelines configuration for HexDAG
# This pipeline handles main codebase and plugin testing

trigger:
  branches:
    include:
      - main
      - develop
      - 'feat/*'
      - 'fix/*'
  paths:
    exclude:
      - '*.md'
      - 'docs/*'
      - 'examples/*'

pr:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.12'
  pipCacheDir: $(Pipeline.Workspace)/.pip

stages:
  - stage: Quality
    displayName: 'Code Quality & Tests'
    jobs:
      - job: LintAndTest
        displayName: 'Lint and Test All Code'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python $(pythonVersion)'

          - task: Cache@2
            inputs:
              key: 'python | "$(Agent.OS)" | pyproject.toml'
              restoreKeys: |
                python | "$(Agent.OS)"
              path: $(pipCacheDir)
            displayName: Cache pip packages

          - script: |
              python -m pip install --upgrade pip uv
              uv sync --all-extras
            displayName: 'Install dependencies'

          - script: |
              uv run ruff check . --config=pyproject.toml --output-format=github
              uv run ruff format . --check
              uv run mypy hexdag/
              uv run bandit -r hexdag/ -f json -o bandit-output.json || true
            displayName: 'Lint and type check'

          - script: |
              # Run main tests
              uv run pytest tests/hexdag/ -v \
                --junitxml=junit/test-results-main.xml \
                --cov=hexdag --cov-report=xml --cov-report=html

              # Run plugin tests if they exist
              for plugin_dir in hexdag_plugins/*/; do
                if [ -d "$plugin_dir/tests" ]; then
                  plugin_name=$(basename "$plugin_dir")
                  uv run pytest "$plugin_dir/tests/" -v \
                    --junitxml=junit/test-results-$plugin_name.xml || true
                fi
              done
            displayName: 'Run all tests'

          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/test-results-*.xml'
              testRunTitle: 'Test Results'
            displayName: 'Publish test results'

          - task: PublishCodeCoverageResults@1
            condition: succeededOrFailed()
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
            displayName: 'Publish code coverage'

  - stage: Integration
    displayName: 'Integration Tests'
    dependsOn: [Quality]
    condition: succeeded()
    jobs:
      - job: IntegrationTests
        displayName: 'Run Integration Tests'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python $(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip uv
              uv sync --all-extras
              # Install all plugins for integration testing if they exist
              if [ -d "hexdag_plugins" ]; then
                for plugin_dir in hexdag_plugins/*/; do
                  if [ -f "$plugin_dir/pyproject.toml" ]; then
                    pip install -e "$plugin_dir"
                  fi
                done
              fi
            displayName: 'Install everything'

          - script: |
              uv run pytest tests/integration/ -v \
                --junitxml=junit/test-results-integration.xml
            displayName: 'Run integration tests'

          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/test-results-integration.xml'
              testRunTitle: 'Integration Tests'
            displayName: 'Publish integration test results'

  - stage: Examples
    displayName: 'Test Examples'
    dependsOn: [Quality]
    condition: succeeded()
    jobs:
      - job: TestExamples
        displayName: 'Run Example Scripts'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python $(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip uv
              uv sync --all-extras
            displayName: 'Install dependencies'

          - script: |
              python scripts/check_examples.py
            displayName: 'Validate examples'
            continueOnError: true
