variables:
- group: pypi-secrets
- name: CI_USERNAME
  value: "CI Pipeline"
- name: CI_EMAIL
  value: developers@omniviser.ai

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: DevelopmentStandards
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - script: |
          # Define your naming convention regex pattern
          PATTERN="(^(chore|ci|docs|experiment|feat|fix|refactor|test)\/[A-Za-z0-9_-]+$)|main|^snyk|^dependabot"

          if [[ $(Build.Reason) == "PullRequest" ]]; then
            BRANCH="$(echo $(System.PullRequest.SourceBranch) | sed 's/refs\/heads\///')"
          else
            BRANCH="$(echo $(Build.SourceBranch) | sed 's/refs\/heads\///')"
          fi

          # Check if the branch name matches the pattern
          if [[ $BRANCH =~ $PATTERN ]]; then
              echo "Branch name '$BRANCH' is valid."
          else
              echo "Branch name [${BRANCH}] does not follow convention: [chore/* | ci/* | dependabot/* | docs/* | experiment/* | feat/* | fix/* | refactor/* | test/* | main | snyk | dependabot]."
              exit 1
          fi
        displayName: "Check the branch name"


      - script: |
          if [ "$BUILD_REASON" == "PullRequest" ] && [ "$TARGETBRANCH" == "refs/heads/main" ]; then
              echo "PullRequest reason for build"
              echo "Main target branch"

              pr_data=$(az repos pr show --id $PULLREQUESTID --organization $ORGANIZATION_URI)
              title=$(echo "$pr_data" | jq -r '.title')
              echo "PR Title: $title"
              echo "Keep in mind that 'Bump' and 'chore' are for AZURE BOTS ONLY, don't use them!"

              pattern="^(ci|docs|experiment|feat|fix|refactor|test|chore|Bump)"

              if [[ "$title" =~ $pattern ]]; then
                  echo "PR title is valid"
              else
                  echo "ERROR: PR TITLE IS INVALID"
                  echo "Please ensure your PR title starts with one of the following prefixes:"
                  echo "ci, Bump, docs, experiment, feat, fix, refactor, test, chore"
                  exit 1
              fi
          fi
        displayName: "Validate PR title"
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
          ORGANIZATION_URI: https://dev.azure.com/omniviser
          PULLREQUESTID: $(System.PullRequest.PullRequestId)
          TARGETBRANCH: $(System.PullRequest.TargetBranch)
          BUILD_REASON: $(Build.Reason)

  - job: CodeQuality
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"
        displayName: "Use Python 3.12"

      - bash: sudo apt-get install graphviz -f
        displayName: Install graphviz

      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install UV"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running Ruff linting with pyproject.toml configuration..."
          uv run ruff check ./hexai --config pyproject.toml
        displayName: "Run Ruff linting (replaces flake8, isort)"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running Ruff formatting check..."
          uv run ruff format ./hexai --check
        displayName: "Run Ruff formatting check (replaces Black)"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running Mypy with pyproject.toml configuration..."
          uv run mypy ./hexai
        displayName: "Run Mypy"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running Pyright with pyproject.toml configuration..."
          uv run pyright ./hexai
        displayName: "Run Pyright"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running tests with pytest configuration from pyproject.toml..."
          # The pytest configuration in pyproject.toml includes:
          # - testpaths = ["tests"]
          # - addopts = "--cov=hexai --cov-report=html --cov-report=term-missing"
          # We override the report formats for Azure DevOps integration
          uv run pytest --cov-report=xml:./coverage.xml --junitxml=./test-results.xml
        displayName: "Run unit tests"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running Bandit for SAST with pyproject.toml configuration..."
          # Bandit configuration from pyproject.toml:
          # exclude_dirs = ["tests", "examples"]
          # skips = ["B101", "B601"]
          uv run bandit -r ./hexai -f json -o bandit-report.json || {
              echo "Bandit found issues or encountered an error. See bandit-report.json for details."
              cat bandit-report.json
              exit 1
          }
        displayName: "Run Bandit"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Checking test structure consistency..."
          uv run scripts/check_test_structure.py
        displayName: "Check test structure consistency"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Checking examples functionality..."
          uv run scripts/check_examples.py
        displayName: "Check examples functionality"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running deptry for dependency analysis..."
          uv run deptry .
        displayName: "Run deptry"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running Safety for dependency vulnerability scanning..."
          # Safety configuration from pyproject.toml:
          # audit-and-monitor = true
          uv run safety check --output json > safety-report.json || {
              echo "Safety found vulnerabilities. See safety-report.json for details."
              cat safety-report.json
              exit 1
          }
        displayName: "Run Safety - dependency vulnerability scan"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running Gitleaks for secret detection..."
          # Install gitleaks - using fixed version for reproducibility
          GITLEAKS_VERSION="8.21.2"
          echo "Installing Gitleaks version: $GITLEAKS_VERSION"
          curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" | tar -xz -C /tmp
          /tmp/gitleaks detect --source . --report-format json --report-path gitleaks-report.json || {
              echo "Gitleaks found secrets or encountered an error. See gitleaks-report.json for details."
              cat gitleaks-report.json
              exit 1
          }
        displayName: "Run Gitleaks - secret detection"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running yamllint for YAML config quality..."
          uv run yamllint -d relaxed .
        displayName: "Run yamllint - YAML config quality"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running vulture for dead code detection with pyproject.toml configuration..."
          # Vulture configuration from pyproject.toml:
          # min_confidence = 90
          # paths = ["hexai"]
          # exclude = ["tests/", "examples/"]
          uv run vulture hexai/ --min-confidence 90
        displayName: "Run vulture - dead code detection"

      - script: |
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Running radon for code complexity analysis with pyproject.toml configuration..."
          # Radon configuration from pyproject.toml:
          # exclude = "tests/*,examples/*"
          # cc_min = "B"
          # show_complexity = true
          uv run radon cc hexai/ --min B --show-complexity
        displayName: "Run radon - code complexity analysis"
