variables:
  - group: pypi-secrets
  - name: CI_USERNAME
    value: "CI Pipeline"
  - name: CI_EMAIL
    value: developers@omniviser.ai

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: DevelopmentStandards
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - script: |
          # Define your naming convention regex pattern
          PATTERN="(^(chore|ci|docs|experiment|feat|fix|refactor|test)\/[A-Za-z0-9_-]+$)|main|^snyk|^dependabot"

          if [[ $(Build.Reason) == "PullRequest" ]]; then
            BRANCH="$(echo $(System.PullRequest.SourceBranch) | sed 's/refs\/heads\///')"
          else
            BRANCH="$(echo $(Build.SourceBranch) | sed 's/refs\/heads\///')"
          fi

          # Check if the branch name matches the pattern
          if [[ $BRANCH =~ $PATTERN ]]; then
              echo "Branch name '$BRANCH' is valid."
          else
              echo "Branch name [${BRANCH}] does not follow convention: \
                [chore/* | ci/* | dependabot/* | docs/* | experiment/* | \
                feat/* | fix/* | refactor/* | test/* | main | snyk | \
                dependabot]."
              exit 1
          fi
        displayName: "Check the branch name"

      - script: |
          if [ "$BUILD_REASON" == "PullRequest" ] && [ "$TARGETBRANCH" == "refs/heads/main" ]; then
              echo "PullRequest reason for build"
              echo "Main target branch"

              pr_data=$(az repos pr show --id $PULLREQUESTID --organization $ORGANIZATION_URI)
              title=$(echo "$pr_data" | jq -r '.title')
              echo "PR Title: $title"
              echo "Keep in mind that 'Bump' and 'chore' are for AZURE BOTS ONLY, don't use them!"

              pattern="^(ci|docs|experiment|feat|fix|refactor|test|chore|Bump)"

              if [[ "$title" =~ $pattern ]]; then
                  echo "PR title is valid"
              else
                  echo "ERROR: PR TITLE IS INVALID"
                  echo "Please ensure your PR title starts with one of the following prefixes:"
                  echo "ci, Bump, docs, experiment, feat, fix, refactor, test, chore"
                  exit 1
              fi
          fi
        displayName: "Validate PR title"
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
          ORGANIZATION_URI: https://dev.azure.com/omniviser
          PULLREQUESTID: $(System.PullRequest.PullRequestId)
          TARGETBRANCH: $(System.PullRequest.TargetBranch)
          BUILD_REASON: $(Build.Reason)

  - job: CIMatrix_Linux_MacOS
    displayName: "Matrix: OS × Python × profiles"
    strategy:
      matrix:
        ubuntu-py310: { vmImage: "ubuntu-latest", python: "3.10" }
        ubuntu-py311: { vmImage: "ubuntu-latest", python: "3.11" }
        ubuntu-py312: { vmImage: "ubuntu-latest", python: "3.12" }
        macos-py310: { vmImage: "macos-latest", python: "3.10" }
        macos-py311: { vmImage: "macos-latest", python: "3.11" }
        macos-py312: { vmImage: "macos-latest", python: "3.12" }
    pool:
      vmImage: $(vmImage)
    variables:
      PACKAGE_NAME: "hexai"
      ARTIFACT_DIR: "artifacts"
      VENV_DIR: ".venv"
    steps:
      - checkout: self
        fetchDepth: 1

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python)"
          addToPath: true
        displayName: "Use Python $(python)"

      - script: |
          if [ "$(Agent.OS)" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y graphviz
          elif [ "$(Agent.OS)" = "Darwin" ]; then
            brew update
            brew install graphviz || true
          else
            echo "Ensure Graphviz installed if needed"
          fi
        displayName: "Install system deps"

      - script: |
          set -e
          curl -LsSf https://astral.sh/uv/install.sh | sh
        displayName: "Install UV (Unix)"

      - script: |
          set -e
          CANDIDATES=("$HOME/.local/bin" "$HOME/.cargo/bin"
                      "/Users/runner/.local/bin" "/Users/runner/.cargo/bin")
          FOUND=""
          for d in "${CANDIDATES[@]}"; do
            if [ -x "$d/uv" ]; then
              FOUND="$d"
              break
            fi
          done
          if [ -z "$FOUND" ]; then
            echo "uv not found in common dirs; listing for debug"
            ls -la "$HOME/.local/bin" || true
            ls -la "$HOME/.cargo/bin" || true
            # fallback
            FOUND="$HOME/.local/bin"
          fi
          echo "Using UV from: $FOUND"
          echo "##vso[task.setvariable variable=UV_BIN_DIR]$FOUND"
        displayName: "Locate UV and set PATH var"

      - script: |
          set -e
          export PATH="$UV_BIN_DIR:$PATH"
          which uv || true
          uv venv
        displayName: "Create UV virtual environment"

      - script: |
          set -e
          mkdir -p $(ARTIFACT_DIR)
        displayName: "Artifacts dir"

      # BASE
      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          echo "=== Install profile: base ==="
          uv pip install -e .
          uv run python -c "import importlib, sys, platform; \
                      importlib.import_module('$(PACKAGE_NAME)'); \
                      print('OK base', sys.version.split()[0], \
                            platform.platform())"
        displayName: "Install (base)"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv pip install -e ".[dev]"
          uv pip install -e ".[viz]"
        displayName: "Install extras [Unix]"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run ruff check ./hexai
        displayName: "Ruff check [Unix]"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run ruff format ./hexai --check
        displayName: "Ruff format --check [Unix]"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run black --check ./hexai
        displayName: "Black --check [Unix]"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run isort ./hexai --check-only
        displayName: "isort --check-only [Unix]"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run mypy ./hexai
        displayName: "mypy [Unix]"


      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          echo "Running tests with coverage..."
          uv run pytest ./tests --cov=./hexai --cov-report=xml:./coverage.xml --junitxml=./test-results.xml
        displayName: "Run unit tests with coverage [Unix]"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          echo "Running Bandit for SAST..."
          uv run bandit -r ./hexai -x ./tests -f json -o bandit-report.json
          BANDIT_EXIT_CODE=$?
          echo "Bandit exit code: $BANDIT_EXIT_CODE"
          if [ $BANDIT_EXIT_CODE -ne 0 ]; then
            echo "Bandit found issues or encountered an error. See bandit-report.json for details."
            cat bandit-report.json
            exit 1
          fi
        displayName: "Run Bandit [Unix]"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run scripts/check_test_structure.py
        displayName: "Check test structure consistency [Unix]"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run scripts/check_examples.py
        displayName: "Check examples functionality [Unix]"

      - script: |
          set -e
          export PATH="$(UV_BIN_DIR):$PATH"
          uv run deptry .
        displayName: "Run deptry [Unix]"

      - script: |
          set -e
          export PATH="$HOME/.local/bin:$PATH"
          echo "Running Safety for dependency vulnerability scanning..."
          uv run safety check --output json > safety-report.json || {
            echo "Safety found vulnerabilities. See safety-report.json for details."
            cat safety-report.json
            exit 1
          }
        displayName: "Run Safety - dependency vulnerability scan"

      - script: |
          set -e
          echo "Running Gitleaks for secret detection..."
          GITLEAKS_VERSION="8.21.2"

          if [[ "$(uname)" == "Darwin" ]]; then
            PLATFORM="darwin_x64"
          else
            PLATFORM="linux_x64"
          fi

          echo "Installing Gitleaks version: $GITLEAKS_VERSION for $PLATFORM"
          curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_${PLATFORM}.tar.gz" | tar -xz -C /tmp # yamllint disable-line rule:line-length
          chmod +x /tmp/gitleaks
          /tmp/gitleaks detect --source . --report-format json --report-path gitleaks-report.json || {
            echo "Gitleaks found secrets or encountered an error. See gitleaks-report.json for details."
            cat gitleaks-report.json
            exit 1
          }
        displayName: "Run Gitleaks - secret detection"

      - script: |
          set -e
          export PATH="$HOME/.local/bin:$PATH"
          echo "Running yamllint for YAML config quality..."
          uv run yamllint -d relaxed .
        displayName: "Run yamllint - YAML config quality [Unix]"

      - script: |
          set -e
          export PATH="$HOME/.local/bin:$PATH"
          echo "Running vulture for dead code detection..."
          uv run vulture hexai/ --min-confidence 90
        displayName: "Run vulture - dead code detection [Unix]"

      - script: |
          set -e
          export PATH="$HOME/.local/bin:$PATH"
          echo "Running radon for code complexity analysis..."
          uv run radon cc hexai/ --min B --show-complexity
        displayName: "Run radon - code complexity analysis"
